name: "Deploy in crate.io"

on: 
  release:
    types: ["created"]
env: 
  CARGO_TERM_COLOR: always

jobs:
  version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Publish package
        run: cargo publish --token ${{ CRATE_IO_TOKEN }}